<?php

namespace App\Imports;


use App\Models\Invoice;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class InvoiceImport implements ToModel, WithHeadingRow
{
    /**
     * @param Collection $collection
     */
    public function model(array $row)
    {
        // dd($row);
        return new Invoice([
            'fin_month' => $row['fin_month'],
            'fin_year' => $row['fin_year'],
            'debtor_acct' => $row['debtor_acct'],
            'name' => $row['name'],
            'block_no' => $row['block_no'],
            'lot_no' => $row['lot_no'],
            'start_date' => $row['start_date'],
            'zone_cd' => $row['zone_cd'],
            'level_no' => $row['level_no'],
            'land_rate' => $row['land_rate'],
            'rentable_area' => $row['rentable_area'],
            'doc_no' => $row['doc_no'],
            'mbal_amt' => $row['mbal_amt'],
            'mbase_amt' => $row['mbase_amt'],
            'mdoc_amt' => $row['mdoc_amt'],
            'mtax_amt' => $row['mtax_amt'],
            'doc_date' => $row['doc_date'],
            'due_date' => $row['due_date'],
            'type_descs' => $row['type_descs'],
            'ref_no' => $row['ref_no'],
            'descs' => $row['descs'],
            'land_area' => $row['land_area'],
            'usage' => $row['usage'],
            'usage_high' => $row['usage_high'],
            'saldo_sblm' => $row['saldo_sblm'],
            'meter_type' => $row['meter_type'],
            'sewage_amt' => $row['sewage_amt'],
            'sewage_percent' => $row['sewage_percent'],
            'min_amt' => $row['min_amt'],
            'last_read' => $row['last_read'],
            'calculation_method' => $row['calculation_method'],
            'curr_read' => $row['curr_read'],
            'capacity' => $row['capacity'],
            'capacity_rate' => $row['capacity_rate'],
            'gen_amt1' => $row['gen_amt1'],
            'usage_rate1' => $row['usage_rate1'],
            'usage_rate2' => $row['usage_rate2'],
            'usage_range1' => $row['usage_range1'],
            'opr_amt1' => $row['opr_amt1'],
            'tax_amt' => $row['tax_amt'],
            'usage_11' => $row['usage_11'],
            'usage_21' => $row['usage_21'],
            'trx_type' => $row['trx_type'],
            'build_up_area' => $row['build_up_area'],
            'currency_cd' => $row['currency_cd'],
            'trx_date' => $row['trx_date'],
            'gen_rate' => $row['gen_rate'],
            'tel_no' => $row['tel_no'],
            'remark' => $row['remark'],
            'balance_amt' => $row['balance_amt'],
            'meter_id' => $row['meter_id'],
            'trx_amt' => $row['trx_amt'],
            'outstanding_we' => $row['outstanding_we'],
            'interest' => $row['interest'],
            'virtual_acct' => $row['virtual_acct'],
            'entity_name' => $row['entity_name'],
            'address1' => $row['address1'],
            'address2' => $row['address2'],
            'address3' => $row['address3'],
            'post_cd' => $row['post_cd'],
            'telephone_no' => $row['telephone_no'],
            'fax_no' => $row['fax_no'],
            'new_descs_ipl' => $row['new_descs_ipl'],
            'new_descs_sf' => $row['new_descs_sf'],
            'outstanding_mf' => $row['outstanding_mf'],
            'fbase_amt' => $row['fbase_amt'],
            'ftax_amt' => $row['ftax_amt'],
            'doc_we' => $row['doc_we'],
            'doc_mf' => $row['doc_mf'],
            'rate_sf' => $row['rate_sf'],
            'descs_gab_1' => $row['descs_gab_1'],
            'descs_gab_2' => $row['descs_gab_2'],
            'bulan_descs' => $row['bulan_descs'],
            'fdoc_amt' => $row['fdoc_amt'],
            'remarks' => $row['remarks'],
            'audit_date' => $row['audit_date'],
            'periode1' => $row['periode1'],
            'periode2' => $row['periode2'],
            'tunggakan_dc' => $row['tunggakan_dc'],
            'tunggakan_ipl' => $row['tunggakan_ipl'],
            'tunggakan_water' => $row['tunggakan_water'],
            'tunggakan_terlambat' => $row['tunggakan_terlambat'],
            'denda_air' => $row['denda_air'],
            'Denda_IPL' => $row['denda_ipl'],
            'Denda_DC' => $row['denda_dc'],
            'rate_ipl' => $row['rate_ipl'],
            'rate_sf1' => $row['rate_sf1'],
            'hand_phone' => $row['hand_phone'],
            'type' => $row['type'],
            'period_water_min' => $row['period_water_min'],
            'period_water_max' => $row['period_water_max'],
            'deposit_ipl' => $row['deposit_ipl'],
            'deposit_dc' => $row['deposit_dc'],
            'freq' => $row['freq'],
            'deposit' => $row['deposit'],
            'ttl_air' => $row['ttl_air'],
            'ttl_ipl_dc' => $row['ttl_ipl_dc'],
            'denda_ppjb_asuransi' => $row['denda_ppjb_asuransi'],
            'outstanding_ppjb_asuransi' => $row['outstanding_ppjb_asuransi'],
            'virtual_acct_real' => $row['virtual_acct_real'],

        ]);
    }
}
